export const get = async () => {
  try {

  }
  catch (error) {
    console.error(error);
  }
}